version: "3"
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.2
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
    - 9200:9200
    environment:
      discovery.type: single-node
    networks:
    - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.2
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
    - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: "http://elastic:9200"
    networks:
    - elasticsearch
  cerberus:
    image: quay.io/openshift-scale/cerberus:latest
    privileged: true
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
       - ./config/cerberus.yaml:/root/cerberus/config/config.yaml:Z  # Modify the config in case of the need to monitor additional components
       - ${HOME}/.kube/config:/root/.kube/config:Z
    networks:
    - elasticsearch

networks:
  elasticsearch: